### ISSUE TITLE
Add job.group and job.name to possible path identifiers

### ISSUE THREAD

**Issue by isuftin** [rundeck-plugins/rundeck-s3-log-plugin#15]
My current S3 write path looks like: `rundeck/${job.project}/${job.id}/${job.execid}.log`

For our operations group, it would be very useful if we could do something like: `rundeck/${job.project}/${job.group}/${job.name}/${job.execid}.log`

However, the group and name params are not currently recognized.

**Comment by gschueler** [comment]
this is pretty simple to add, however for adhoc commands, there is no job group or name....

**Comment by gschueler** [comment]
any blank path components are collapsed, so for an adhoc command the pattern

    rundeck/${job.project}/${job.group}/${job.name}/${job.execid}.log

would basically become

    rundeck/${job.project}/${job.execid}.log

is that ok?
