### ISSUE TITLE
Wrong version number in the file name

### ISSUE THREAD

**Issue by leshik** [rundeck-plugins/rundeck-s3-log-plugin#35]
The latest v1.0.9 has an incorrect version number in the file name:

<img width="408" alt="Screenshot 2020-03-19 13 42 54" src="https://user-images.githubusercontent.com/443678/77039072-bd267f00-69e7-11ea-8db1-fe4653b6d40a.png">

**Comment by leshik** [comment]
@gschueler same with v1.0.10 – it looks weird...

**Comment by gschueler** [comment]
It looks like the project version was incorrectly hardcoded here:

https://github.com/rundeck-plugins/rundeck-s3-log-plugin/blame/master/build.gradle#L42

@ltamaster

**Comment by ltamaster** [comment]
@leshik  Please check the last release
