### ISSUE TITLE
Which license is governing this project?

### ISSUE THREAD

**Issue by rzheleva** [rundeck-plugins/rundeck-s3-log-plugin#40]
Hello Team, 

May you please advise which open source license is governing the rundeck-s3-log-plugin project?

Also, may you please update the repo and add a license file?

Thanks, 
Radi

**Comment by rzheleva** [comment]
Hi Team, 

May you please advise on the question above?

Thanks, 
Radi

**Comment by rzheleva** [comment]
Hi Team,

May you please advise what is the project open source license?

**Comment by rzheleva** [comment]
May you please look at this issue?

**Comment by fdevans** [comment]
It would fall under Apache 2.  We will try to add it in the near future.
